// ===============  Product  =============== //
// Person & Professions
export const GET_PRODUCTS_REQUEST_START = "GET_PRODUCTS_REQUEST_START"
export const POST_PRODUCT_REQUEST_START = 'POST_PRODUCT_REQUEST_START'
export const PUT_PRODUCT_REQUEST_START = 'PUT_PRODUCT_REQUEST_START'
export const DELETE_PRODUCT_REQUEST_START = 'DELETE_PRODUCT_REQUEST_START'

export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_LATEST_PRODUCTS = 'SET_LATEST_PRODUCTS'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const CHANGE_PRODUCT_PICTURE = 'CHANGE_PRODUCT_PICTURE'
// ===============  Vacancy  =============== //
export const GET_VACANCIES_REQUEST_START = 'GET_VACANCIES_REQUEST_START'
export const POST_VACANCY_REQUEST_START = 'POST_VACANCY_REQUEST_START'
export const PUT_VACANCY_REQUEST_START = 'PUT_VACANCY_REQUEST_START'
export const DELETE_VACANCY_REQUEST_START = 'DELETE_VACANCY_REQUEST_START'

export const SET_VACANCIES = 'SET_VACANCIES'
export const ADD_VACANCY = 'ADD_VACANCY'
export const EDIT_VACANCY = 'EDIT_VACANCY'
export const REMOVE_VACANCY = 'REMOVE_VACANCY'
// ===============  Category  =============== //
export const GET_CATEGORY_SHORTLIST_REQUEST_START = "GET_CATEGORY_SHORTLIST_REQUEST_START"
export const SET_CATEGORY_SHORTLIST = 'SET_CATEGORY_SHORTLIST'



// Common
export const REQUEST_FAILED = 'REQUEST_FAILED'